Music-Server:
  BootApp:
    - SwowCloud\WebSocket\Config\ConfigProvider
    - SwowCloud\WebSocket\Event\EventProvider
    - SwowCloud\WebSocket\Logger\LoggerProvider
    - SwowCloud\WebSocket\Server\ServerProvider
