WebSocket-Server:
  BootApp:
    - SwowCloud\WsServer\Config\ConfigProvider
    - SwowCloud\WsServer\Event\EventProvider
    - SwowCloud\WsServer\Logger\LoggerProvider
    - SwowCloud\WsServer\Server\ServerProvider
